/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <gmp.h>
#include <stdlib.h>
/* Header for class GmpInteger */

#ifndef _Included_GmpInteger
#define _Included_GmpInteger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GmpInteger
 * Method:    mpz_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GmpInteger_mpz_1init
  (JNIEnv * env, jobject self) {
    mpz_ptr underlying = (mpz_ptr)malloc(sizeof(__mpz_struct));
    mpz_init(underlying);

    jclass thisClass = env -> GetObjectClass(self);
    jfieldID pointerField = env->GetFieldID(thisClass, "pointer", "J");
    env->SetLongField(self, pointerField, (jlong)underlying);
  }

/*
 * Class:     GmpInteger
 * Method:    mpz_clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_GmpInteger_mpz_1clear
  (JNIEnv * env, jobject obj, jlong src){
    mpz_clear((mpz_ptr)src);
    free((mpz_ptr)src);
  }

/*
 * Class:     GmpInteger
 * Method:    mpz_mul_si
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_GmpInteger_mpz_1mul_1si
  (JNIEnv * env, jclass thisClass, jlong dest, jlong source, jint val){
    mpz_mul_si((mpz_ptr)dest, (mpz_srcptr)source, val);
  }

/*
 * Class:     GmpInteger
 * Method:    mpz_add
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_GmpInteger_mpz_1add
  (JNIEnv *env, jclass thisClass, jlong dest, jlong src, jlong value) {
    mpz_add((mpz_ptr)dest, (mpz_srcptr)src, (mpz_srcptr)value);
  }

/*
 * Class:     GmpInteger
 * Method:    mpz_tdiv_q
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_GmpInteger_mpz_1tdiv_1q
  (JNIEnv * env, jclass thisClass, jlong dest, jlong src, jlong value){
    mpz_tdiv_q((mpz_ptr)dest, (mpz_srcptr)src, (mpz_srcptr)value);
  }

/*
 * Class:     GmpInteger
 * Method:    mpz_set_si
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_GmpInteger_mpz_1set_1si
  (JNIEnv * env, jclass thisClass, jlong dest, jint value){
    mpz_set_si((mpz_ptr)dest, value);
  }

/*
 * Class:     GmpInteger
 * Method:    mpz_get_si
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_GmpInteger_mpz_1get_1si
  (JNIEnv * env, jclass thisClass, jlong dest){
    return mpz_get_si((mpz_ptr)dest);
  }

/*
 * Class:     GmpInteger
 * Method:    mpz_get_d
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_GmpInteger_mpz_1get_1d
  (JNIEnv * env, jclass thisClass, jlong dest){
    return mpz_get_d((mpz_ptr)dest);
  }

#ifdef __cplusplus
}
#endif
#endif
